package com.giphytest.bean;

import java.io.Serializable;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.apihint.Internal;

@Entity
public class GiphyImageInfo implements Serializable {

    @Id
    private long id;

    private String giphyId;
    private String url;
    private String videoUrl;
    private String totalUpVote;
    private String totalDownVote;


    @Generated(2062543097)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public GiphyImageInfo(long id, String giphyId, String url, String videoUrl,
            String totalUpVote, String totalDownVote) {
        this.id = id;
        this.giphyId = giphyId;
        this.url = url;
        this.videoUrl = videoUrl;
        this.totalUpVote = totalUpVote;
        this.totalDownVote = totalDownVote;
    }

    @Generated(831393918)
    public GiphyImageInfo() {
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(final String url) {
        this.url = url;
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getTotalUpVote() {
        return totalUpVote;
    }

    public void setTotalUpVote(String totalUpVote) {
        this.totalUpVote = totalUpVote;
    }

    public String getTotalDownVote() {
        return totalDownVote;
    }

    public void setTotalDownVote(String totalDownVote) {
        this.totalDownVote = totalDownVote;
    }

    public String getGiphyId() {
        return giphyId;
    }

    public void setGiphyId(String giphyId) {
        this.giphyId = giphyId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }

        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        final GiphyImageInfo that = (GiphyImageInfo) o;

        return url != null ? url.equals(that.url) : that.url == null;

    }

    @Override
    public int hashCode() {
        return url != null ? url.hashCode() : 0;
    }
}
